---

- name: Provision Raspberrys OS Level
  hosts: cluster
  become: true
  gather_facts: true
  #vars_files: group_vars/provision_all_secret.yml
    #  pre_tasks:
    #    - include_tasks: debug_vars.yml
  roles:
    - ansible-provision-rpis
    - ansible-k8s-install



- name: Deploy applications at K8S
  hosts: master
  become: true
  gather_facts: true
  roles:
    - ansible-k8s-deploy

