---

######################### Variables para rol ansible-provision-rpis ##############################


provision_netplan_configure: true
netplan_remove_existing: true

provision_cluster_user: "carmen"

provision_rpis_cluster:
  - { name: "{{ hostvars['master'].ansible_hostname }}", ip: "{{ hostvars['master'].node_ip }}" } 
  - { name: "{{ hostvars['worker1'].ansible_hostname }}", ip: "{{ hostvars['worker1'].node_ip }}" }
  - { name: "{{ hostvars['worker2'].ansible_hostname }}", ip: "{{ hostvars['worker2'].node_ip }}" }

#Listado de paquetes a instalar en todas las máquinas
provision_rpis_packages: ['vim','curl','wget','iproute2','nfs-common','python3-pip','nfs-kernel-server','apache2-utils']


#Variables para instalación y configuración de postfix
provision_postfix: true

provision_mail_from: "karmengc@gmail.com"
provision_mail_certificate: ""
provision_mail_smarthost: "smtp.gmail.com"
provision_mail_smarthost_port: "587"
provision_mail_localsmtp: false

#Generar certificado autofirmado en master
provision_master_selfcert: true

#Variables para montar directorio del host principal por NFS en todas las RPis
provision_host_ip: "192.168.1.37"
provision_host_nfs_dir_exported: "/home/carmen/UPO/TFM/nfs"
provision_nfs_host_mount: true
provision_nfs_host_share_mounts:
  - path: /mnt/nfs
    location: "{{ provision_host_ip }}:{{ provision_host_nfs_dir_exported }}"
    opts: rw

# Exportar desde el Master carpetas NFS hacia los nodos
provision_master_nfs2nodes: true

# Carpetas a exportar para compartir el certificado de master e instalarlo en los nodos
provision_nfs_master_share_mounts:
  - path: /opt/certs
    location: "{{ provision_rpis_cluster[0].ip }}:/opt/certs"
    opts: rw
  - path: /opt/registry
    location: "{{ provision_rpis_cluster[0].ip }}:/opt/registry"
    opts: rw
  - path: /opt/auth
    location: "{{ provision_rpis_cluster[0].ip }}:/opt/auth"
    opts: rw
  - path: /nfs/exports/mattermost-postgres-pv
    location: "{{ provision_rpis_cluster[0].ip }}:/export/nfs/mattermost-postgres-pv"
    opts: rw
  - path: /nfs/exports/drupal-pv
    location: "{{ provision_rpis_cluster[0].ip }}:/export/nfs/drupal-pv"
    opts: rw
  - path: /nfs/exports/pv0
    location: "{{ provision_rpis_cluster[0].ip }}:/export/nfs/pv0"
    opts: rw
  - path: /nfs/exports/pv1
    location: "{{ provision_rpis_cluster[0].ip }}:/export/nfs/pv1"
    opts: rw
  - path: /nfs/exports/pv2
    location: "{{ provision_rpis_cluster[0].ip }}:/export/nfs/pv2"
    opts: rw

# Montar carpetas de master en los nodos q contienen el certificado
provision_nfs_master_exports: [ "/opt/certs *(rw,sync,no_root_squash)", "/opt/registry *(rw,sync,no_root_squash)", "/opt/auth *(rw,sync,no_root_squash)", "/export/nfs/mattermost-postgres-pv *(rw,sync,no_root_squash)", "/export/nfs/drupal-pv *(rw,sync,no_root_squash)", "/export/nfs/pv0 *(rw,sync,no_root_squash)", "/export/nfs/pv1 *(rw,sync,no_root_squash)", "/export/nfs/pv2 *(rw,sync,no_root_squash)"]

#No desactivamos swap, puesto que en la imagen elegida viene desactivada por defecto
provision_disable_swap: false
provision_swap_file_path: ""


# vim: ff=unix:ai:et:sw=2:ts=2:
