---

cluster_arch: "amd64"

fqdn: cluster.local
deployment_dir: "{{ ansible_env.HOME }}/deployment"
app_log_volume: "/var/log/{{ app_name }}"

apps_to_deploy: {'myweb':'8080', 'mattermost':'8000'}
kubernetes_create_admin_dashb_user: true

