---

#ansible_python_interpreter: '{{ ansible_playbook_python }}'

#provision_cluster_user: "vagrant"
provision_cluster_user: "vagrant"
provision_cluster_user_passwd: "vagrant"
provision_netplan_configure: false
provision_master_selfcert: true

provision_rpis_cluster:
  - { name: "master", ip: "192.168.130.150" } 
  - { name: "worker1", ip: "192.168.130.151" }
  - { name: "worker2", ip: "192.168.130.152" }

provision_rpis_packages: ['vim','curl','wget','iproute2','nfs-common','python3-pip','nfs-kernel-server','apache2-utils']

provision_postfix: true

provision_mail_from: "karmengc@gmail.com"
provision_mail_certificate: ""
provision_mail_smarthost: "smtp.gmail.com"
provision_mail_smarthost_port: "587"
provision_mail_localsmtp: false

#Montar directorio desde el host desde el que se despliega en todos los nodos
provision_host_ip: "192.168.130.1"
provision_host_nfs_dir_exported: "/home/carmen/UPO/TFM/nfs"
provision_nfs_host_mount: true
provision_nfs_host_share_mounts:
  - path: /mnt/nfs
    location: "{{ provision_host_ip }}:{{ provision_host_nfs_dir_exported }}"
    opts: rw

# Exportar desde el Master carpetas NFS hacia los nodos
provision_master_nfs2nodes: true

# Carpetas a exportar para compartir el certificado de master e instalarlo en los nodos
provision_nfs_master_share_mounts:
  - path: /opt/certs
    location: "{{ provision_rpis_cluster[0].ip }}:/opt/certs"
    opts: rw
  - path: /opt/registry
    location: "{{ provision_rpis_cluster[0].ip }}:/opt/registry"
    opts: rw
  - path: /opt/auth
    location: "{{ provision_rpis_cluster[0].ip }}:/opt/auth"
    opts: rw
  - path: /nfs/exports/mattermost-postgres-pv
    location: "{{ provision_rpis_cluster[0].ip }}:/export/nfs/mattermost-postgres-pv"
    opts: rw
  - path: /nfs/exports/drupal-pv
    location: "{{ provision_rpis_cluster[0].ip }}:/export/nfs/drupal-pv"
    opts: rw
      #  - path: /nfs/exports/drupal-pv-db
      #    location: "{{ provision_rpis_cluster[0].ip }}:/export/nfs/drupal-pv-db"
      #    opts: rw
  - path: /nfs/exports/pv0
    location: "{{ provision_rpis_cluster[0].ip }}:/export/nfs/pv0"
    opts: rw
  - path: /nfs/exports/pv1
    location: "{{ provision_rpis_cluster[0].ip }}:/export/nfs/pv1"
    opts: rw
  - path: /nfs/exports/pv2
    location: "{{ provision_rpis_cluster[0].ip }}:/export/nfs/pv2"
    opts: rw

# Montar carpetas de master en los nodos q contienen el certificado
#provision_nfs_master_exports: [ "/opt/certs *(rw,sync,no_root_squash)", "/opt/registry *(rw,sync,no_root_squash)", "/opt/auth *(rw,sync,no_root_squash)", "/export/nfs/mattermost-postgres-pv *(rw,sync,no_root_squash)", "/export/nfs/drupal-pv *(rw,sync,no_root_squash)", "/export/nfs/drupal-pv-db *(rw,sync,no_root_squash)" ]
provision_nfs_master_exports: [ "/opt/certs *(rw,sync,no_root_squash)", "/opt/registry *(rw,sync,no_root_squash)", "/opt/auth *(rw,sync,no_root_squash)", "/export/nfs/mattermost-postgres-pv *(rw,sync,no_root_squash)", "/export/nfs/drupal-pv *(rw,sync,no_root_squash)", "/export/nfs/pv0 *(rw,sync,no_root_squash)", "/export/nfs/pv1 *(rw,sync,no_root_squash)", "/export/nfs/pv2 *(rw,sync,no_root_squash)"]


#No desactivamos swap, puesto que en la imagen elegida viene desactivada por defecto
provision_disable_swap: false
provision_swap_file_path: ""

