---
provision_rpis_cluster:
  - { name: "master", ip: "192.168.130.150" } 
  - { name: "worker1", ip: "192.168.130.151" }
  - { name: "worker2", ip: "192.168.130.152" }

provision_rpis_packages: ['vim','curl','wget','iproute2']

provision_postfix: true

provision_mail_from: "karmengc@gmail.com"
provision_mail_certificate: ""
provision_mail_smarthost: "smtp.gmail.com"
provision_mail_smarthost_port: "587"
provision_mail_localsmtp: false

