---

- name: Use iptables-legacy instead of nftables
  alternatives:
    name: '{{ item.name }}'
    path: '{{ item.path }}'
  with_items:
    - { name: iptables, path: /usr/sbin/iptables-legacy }
    - { name: ip6tables, path: /usr/sbin/ip6tables-legacy }

# See https://www.jeffgeerling.com/k8s-cni-virtualbox
- name: Retrieve current flannel manifest from Github
  get_url:
    url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    dest: ~/kube-flannel.yml
  when: inventory_hostname == 'master'

- name: Patch Flannel Manifest with VirtualBox interface
  patch:
    src: files/kube-flannel-patch.txt
    dest: ~/kube-flannel.yml
  when: inventory_hostname == 'master'

- name: Set the correct path for the patched Flannel manifest
  set_fact:
    kubernetes_flannel_manifest_file: ~/kube-flannel.yml
  when: inventory_hostname == 'master'

